---
# Main tasks file for fubarhouse.nodejs

- name: "Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is not defined

- name: "Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined and fubarhouse_user is not defined

- name: "Get $HOME"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "echo $HOME"
  register: shell_home_dir
  changed_when: false
  when: fubarhouse_user_dir is not defined

- name: "Set $HOME"
  set_fact:
    fubarhouse_user_dir: "{{ shell_home_dir.stdout }}"
  when: fubarhouse_user_dir is not defined

- name: "Set default ivm installation directory"
  set_fact:
    ivm_install_dir: "{{ fubarhouse_user_dir }}/.ivm"
  when:
  - ivm_install_dir is not defined
  - install_ivm|bool == true

- name: "Set default nvm installation directory"
  set_fact:
    nvm_install_dir: "{{ fubarhouse_user_dir }}/.nvm"
  when:
  - nvm_install_dir is not defined
  - install_nvm|bool == true

- include: nvm.yml
  when: install_nvm

- include: ivm.yml
  when:
    - install_ivm == true
    - '"{{ ansible_os_family }}" != "Darwin"'

- include: nodejs.yml
  when: install_nodejs == true

- include: iojs.yml
  when:
    - install_iojs == true
    - '"{{ ansible_os_family }}" != "Darwin"'

- include: npm.yml
  when: install_npm == true