language: python
python: '3.6'
sudo: required
env:
- CONTAINER_ID=$(mktemp)
branches:
  only:
  - master
services:
- docker
before_install:
- sudo docker pull centos:7
- sudo docker build --rm=true --file=Dockerfile --tag=centos:ansible .
script:
- sudo docker run --detach --privileged --volume="${PWD}":/WunderMachina:rw --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro
  centos:ansible /usr/lib/systemd/systemd > "${CONTAINER_ID}"
- sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory
  /WunderMachina/tests/test.yml --syntax-check || (echo 'Ansible playbook syntax
  check failed' && exit 2 )
- sudo docker exec "$(cat ${CONTAINER_ID})" ansible-playbook -i /WunderMachina/tests/test-inventory
  /WunderMachina/tests/test.yml -vvv --connection=local --sudo || ( echo 'First
  run failed' && exit 2 )
- sudo docker stop "$(cat ${CONTAINER_ID})"
- sudo docker rm "$(cat ${CONTAINER_ID})"
notifications:
  email: false
  slack:
    secure: oItptZ/DZnX+gaZl1xXs5KaLBo4HUFsLsgrJ6CVm9Lq0Luv7809yK0zz6na/HHGKVUnNOJs8IqQWEy9woAcKhniGcmOC7uAm1aovJCPHp5RmRip4/xu2jhQMCo1mL5od1tuOWPR6SS1GzYw3mUl5SunmDAO1iYq/qXXX2EHiW9gCZHpFac9PUaQmOr0jJWvnGEOAjZ7LckiIv+nOuhWQfDe0qZtarIMlgxvhRdHM8bhAHq0eAm/MV4QRwQ6Vz0iVwvjTZeU2WykRtCq0eqvpwEUHK+ahsT3ZSXSFaoPSQ3OTaaqUKNHT6IbGLKrb0jeCJn8zsBS3SAzkt7FY1h/i96K8ifM4bE5918ZtgReQc9W4LDERHQolyhZu3l4Sv8JQaJPNqM6d1sQ5Xre8xa/h08LscKhIi5/jvaepU6yY0GfXIHz6FSoUo0AcRMplQGPcRLqNmiSeG1c+jl/ns4GSN94cwappYusKH7JHIjm2Tt5GpVmE9rT3Mqofy0ouRc9WoyN9jz7fMlxoBhyhTU2UU5bUXsZCAafp9fRao3t84ZFbSlvl4MtOlLnI0p1PYAGKYr6FxbhHC6zjx0ImlG7VvUwFqSTO+mEJYl+yVCKkVJfm1KxKxSr5e3kEdcouMUvk8U6zVGVjj9hOxMvM5+T8DakdXnFa4IAsp9cr4U+XvI8=
