---

# Setup all of our php-fpm related repositories.


- name: Make sure epel-release & yum-utils are installed.
  yum: pkg={{item}} state=present
  with_items:
    - epel-release
    - yum-utils

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
  when: distro == "rhel7"

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
  when: distro == "centos7"


- name: Update Remi repo. Disable other PHP versions  and enable 7.4 then run yum clean all.
  become: yes
  become_user: root
  shell: |
    yum-config-manager --disable remi-php54
    yum-config-manager --disable remi-php72
    yum-config-manager --disable remi-php73
    yum-config-manager --disable remi-php71
    yum-config-manager --enable remi-php74
    yum clean all






# Mariadb repository for client
- copy:
    src=mariadb/mariadb.repo
    dest=/etc/yum.repos.d/mariadb.repo
