---

# Setup all of our php-fpm related repositories.

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://repo.ius.io/ius-release-el7.rpm"
  when: distro == "rhel7"

- name: Install repositories
  yum: pkg={{item}} state=present
  with_items:
    - "https://repo.ius.io/ius-release-el7.rpm"
  when: distro == "centos7"

# Mariadb repository for client
- copy:
    src=mariadb/mariadb.repo
    dest=/etc/yum.repos.d/mariadb.repo
